#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Crear 5 espacios de trabajo con iconos
bspc monitor -d 1 2 3 4 5

# Asignar iconos a los espacios de trabajo
ws-icon-0 =   ; Ícono de terminal (U+e795)
ws-icon-1 =   ; Ícono de navegador (U+f738)
ws-icon-2 =   ; Ícono de carpeta (U+f07c)
ws-icon-3 =   ; Ícono de imagen (U+f03e)
ws-icon-4 =   ; Ícono de música (U+f001)

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom &
polybar &
xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x1080 --rotate normal --output DP-1 --off --output DP-2 --off --output DP-3 --off --output DP-4 --off --output DP-5 --off --output DP-6 --off --output DP-7 --off --output DP-8 --off --output HDMI-1-1 --mode 1920x1080 --pos 0x0 --rotate normal
feh --bg-scale ~/wallpapers/Minimalist/alena-aenami-around-us.jpg
udiskie %

